# Web Technology Stack Probing Script
# Run this script when the backend server is running

$outputFile = "recon/stack_inventory.md"
$baseUrl = "http://localhost:8000"

Write-Host "Probing web technology stack at $baseUrl..."
Write-Host ""

# Create results section
$results = "## Automated Probing Results`n`n"
$results += "### Probing Date`n"
$results += "$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')`n`n"
$results += "### HTTP Headers`n"

try {
    # Get root endpoint
    Write-Host "Probing root endpoint..."
    $response = Invoke-WebRequest -Uri $baseUrl -UseBasicParsing -ErrorAction Stop
    
    $results += "`n**Status Code:** $($response.StatusCode)`n"
    $results += "**Server:** $($response.Headers.Server)`n"
    $results += "**Content-Type:** $($response.Headers.'Content-Type')`n`n"
    $results += "**All Headers:**`n"
    
    foreach ($header in $response.Headers.GetEnumerator()) {
        $results += "  - $($header.Key): $($header.Value)`n"
    }
    
    Write-Host "Root endpoint probed successfully"
} catch {
    $results += "`n**Error:** $($_.Exception.Message)`n"
    Write-Host "Failed to probe root endpoint: $($_.Exception.Message)"
}

$results += "`n### API Documentation Endpoints`n"

# Probe /docs endpoint
try {
    Write-Host "Probing /docs endpoint..."
    $docsResponse = Invoke-WebRequest -Uri "$baseUrl/docs" -UseBasicParsing -ErrorAction Stop
    $results += "`n**/docs (Swagger UI):** Status $($docsResponse.StatusCode) - FastAPI detected`n"
    Write-Host "/docs endpoint found (FastAPI indicator)"
} catch {
    $results += "`n**/docs:** Not accessible or error`n"
    Write-Host "/docs endpoint not accessible"
}

# Probe /redoc endpoint
try {
    Write-Host "Probing /redoc endpoint..."
    $redocResponse = Invoke-WebRequest -Uri "$baseUrl/redoc" -UseBasicParsing -ErrorAction Stop
    $results += "`n**/redoc (ReDoc):** Status $($redocResponse.StatusCode) - FastAPI detected`n"
    Write-Host "/redoc endpoint found (FastAPI indicator)"
} catch {
    $results += "`n**/redoc:** Not accessible or error`n"
}

# Probe /openapi.json
try {
    Write-Host "Probing /openapi.json endpoint..."
    $openapiResponse = Invoke-WebRequest -Uri "$baseUrl/openapi.json" -UseBasicParsing -ErrorAction Stop
    $openapiData = $openapiResponse.Content | ConvertFrom-Json
    $results += "`n**/openapi.json:** Status $($openapiResponse.StatusCode)`n"
    $results += "- Title: $($openapiData.info.title)`n"
    $results += "- Version: $($openapiData.info.version)`n"
    Write-Host "/openapi.json found - FastAPI confirmed"
} catch {
    $results += "`n**/openapi.json:** Not accessible`n"
}

$results += "`n### API Endpoint Probes`n"

# Probe /api/v1/courses
try {
    Write-Host "Probing /api/v1/courses endpoint..."
    $coursesResponse = Invoke-WebRequest -Uri "$baseUrl/api/v1/courses" -UseBasicParsing -ErrorAction Stop
    $results += "`n**/api/v1/courses:** Status $($coursesResponse.StatusCode) - API endpoint accessible`n"
    Write-Host "/api/v1/courses accessible"
} catch {
    $statusCode = if ($_.Exception.Response) { $_.Exception.Response.StatusCode.value__ } else { "Unknown" }
    $results += "`n**/api/v1/courses:** Status $statusCode - $($_.Exception.Message)`n"
}

# Probe /health
try {
    Write-Host "Probing /health endpoint..."
    $healthResponse = Invoke-WebRequest -Uri "$baseUrl/health" -UseBasicParsing -ErrorAction Stop
    $results += "`n**/health:** Status $($healthResponse.StatusCode) - $($healthResponse.Content)`n"
    Write-Host "/health endpoint found"
} catch {
    $results += "`n**/health:** Not accessible`n"
}

$results += "`n### Technology Detection Summary`n"

# Detect technologies based on responses
$techDetected = @()

if ($docsResponse -and $docsResponse.StatusCode -eq 200) {
    $techDetected += "FastAPI (via /docs endpoint)"
}
if ($redocResponse -and $redocResponse.StatusCode -eq 200) {
    $techDetected += "FastAPI (via /redoc endpoint)"
}
if ($response -and $response.Headers.Server -like "*uvicorn*") {
    $techDetected += "Uvicorn ASGI Server"
}

foreach ($tech in $techDetected) {
    $results += "- $tech`n"
}

$results += "`n### Response Analysis`n"

if ($response) {
    $results += "`n**Root Endpoint Response:**`n"
    $results += "- Status: $($response.StatusCode)`n"
    $results += "- Content Length: $($response.RawContentLength) bytes`n"
    $results += "- Response Time: < 1s (local)`n"
}

$results += "`n---`n`n"
$results += "*Results generated by automated probing script*`n"

# Append to file
$results | Add-Content -Path $outputFile -Encoding UTF8

Write-Host ""
Write-Host "Results saved to $outputFile"
Write-Host "Check the 'Automated Probing Results' section"

